fac-31/Pro0217-BookRecommender

controllers/bookController.js
controllers/recommendController.js
controllers/userController.js
models/Book.js
models/Recommendation.js
models/User.js
package-lock.json
package.json
public/index.html
routes/bookRoutes.js
routes/recommendRoutes.js
routes/userRoutes.js
server.js

Hello,
I created routes and controllers for future work as the structure of the MVC application.
right now they're empty.
I still need to think about views - not fully understood yet on how views integrate.
At the moment, there's a index.html at public directory in the same way we have worked so far.

Basic project structure

---

controllers/recommendController.js
googleBooksAPIWrapper.js
server.js

added a basic wrapper that gets a list of titles and returns a list of webURLS of the cover for these titles.

googleBooks API wrapper

---

api_examples/recommendations_POST.rest
config/openai.js
controllers/recommendController.js
models/Book.js
models/Recommendation.js
package-lock.json
package.json
routes/recommendRoutes.js
services/openAiService.js

- Added a config file for setting up the openAi api with the key from the .env
- Created openAiService.js file for calling the openAi api and returning the json
- Updated the model for a Book, which becomes the structure for openAi response
- added an example of the api in action in api_examples

Getting ai recommendations

---

controllers/recommendController.js
googleBooksAPIWrapper.js
public/index.html
public/script.js
server.js

Hello,
added the integration
The temporary json that is returned to the frontend is the array:
[
{ 
"recommendation":  { title, author, year, reason_for_recommendation } 
"cover": webURL 
},
...
]
I've added a very simple frontend with submit and console.log() that prints the return value.

integrating the two services

---

controllers/bookController.js
controllers/userController.js
db.json
models/api.js
package-lock.json
package.json
routes/userRoutes.js
server.js

Makes use of `json-server` to manage users.We route the `json-server` params to the `/api/` url so `fetchAPI` function can make use of it. Done all of the actions at `userController.js` in a simplistic way where it very much can be improved/expanded.
I'm not sure if we'll ever use `models/User.js`, so that could be delete. And whenever if there a better place to put `models/api.js` at.

Use json-server to manage users in db.json

---

models/Recommendation.js
models/User.js
models/schemas/bookSchema.js
models/schemas/userSchema.js
services/googleBooksAPIWrapper.js

In addition, starting on injection prompt based on user likes, not yet active.

changed ISBN to ID (ISBN is not guaranteed). 

---

api_examples/users_book_POST.rest
controllers/userController.js
routes/userRoutes.js
server.js

See api_examples/users_book_POST.rest` on how to pass in params

Add API to add/remove likes/dislikes books

---

api_examples/fetchBooksByKey_POST.rest
controllers/bookController.js
public/myBooks/index.html
public/myBooks/script.js
routes/bookRoutes.js

`/books/fetchBooksByKey` API allows to fetch all of the books ordered by most likes or dislikes.
Added some commented code in `/public/myBooks` for a brief test, ideally that whole page should be converted into a template to easily reuse it, but that's for another time.

Add API to get list of books ordered by key counts

---

test.js

added workflow folder so it should work now

---

public/frontstyles.css
public/index.html
public/library-interior/friends.js
public/library-interior/index.html
public/styles.css
public/theirBooks/script.js

Added buttons to unfriend users in friend list

Unfriend buttons

---

package-lock.json
package.json
public/index.ejs
public/library-interior/index.ejs
public/myBooks/index.ejs
public/templates/head.ejs
public/templates/navbar.ejs
public/theirBooks/index.ejs
server.js

Currently got `head.ejs` and `navbar.ejs` for html to reuse it

Add html templates to reuse it

---

controllers/recommendController.js
controllers/userController.js
models/Recommendation.js
models/api.js
models/schemas/userSchema.js
public/library-front-script.js
public/library-interior/script.js
public/myBooks/script.js
public/templates/navbar.ejs
public/theirBooks/script.js
public/universal-script.js

created a new PR according to Connor's PR review, thank you :)
also removed logs
also appended "/" at ends of re-directs for compatibility with Edge browser

Book data id and recommendation

---

public/library-interior/script.js
public/myBooks/script.js
public/universal-script.js

two functionalities added:
1. the correct reason is now displayed on the librarian dialogue.
2. The reading list is updated immediately when the user likes a recommendation from the container below it. I sent in a parameter which is the fetchUsersBooks function that populates the reading list, this is passed down to the async handler of judgmentPassed, so it is called from there and voila.
I even remembered to format prettier :)

Update reading list

---

tests/create-user.spec.js
tests/recommendations.spec.js

One for user creation and friends, and another for recommendations and liking

Add 2 more tests

---

api_examples/users_GET.rest
package-lock.json
package.json
server.js
swagger.js
swagger.yaml

started to document in swagger.yaml all the entry points into the backend

Swagger doc

---

public/styles.css
public/universal-script.js

Only for recommendations for now, and would like to do more to it, but thats for another day.

Animate book disappearing on like/dislike

---

models/api.js
package-lock.json
package.json

Mutex the db, so only one user has access at a time.
this will hopefully allow multiple user to access the the same db.json for deployment for example so we could all test the deployment or work on it concurrently.

Lock db json

---

controllers/recommendController.js
models/Recommendation.js
public/library-interior/script.js
public/myBooks/script.js
public/theirBooks/script.js
public/universal-script.js
services/openAiService.js

- Add more smoother animations when selecting a book in more pages.
- Refactor code to have book creation done in one function.
- Recommend another book when one of the book has been selected.

Add more animations, recommend more books, and merge book creations into one.

---

.gitignore
public/myBooks/script.js
public/universal-script.js
tests/create-user.spec.js
tests/example.spec.js
tests/friends.spec.js
tests/recommendations.spec.js

Added a test for the friend request system. Updated the recommendations test to check that the specific book that’s liked gets added to the user’s reading list and that the recommendations based on their reading list populate correctly.
To allow selection of specific books, I modified the myBooks/script.js so that the book ID is added as an attribute upon creation, which is then referenced in the tests.
During the previous refactoring, a minor bug was introduced where the text wasn’t changing from "I've got just the books you might like! They're around here somewhere..." to "Based on your reading list, you might like these!"—this has now been fixed.
and added TESTdb.json to the gitignore

Test improvements 

---

.github/workflows/discord.yml

Uses discord webhook, which has been added as a secret

feat: added Github workflow to notify discord on pull requests

---

controllers/recommendController.js
models/Recommendation.js
public/myBooks/script.js

Follows the same kind of way recommendations works, display a new book in myBooks after selecting such one

Recommends new books in myBooks after selecting one

---

.github/workflows/discord.yml
package.json
public/myBooks/index.ejs
public/theirBooks/index.ejs

Added Wallace and Gromit tribute easter egg (just a command line call and response) and inbox.js script to myBooks and theirBooks pages.

Final UI edits

---

docs/api.json
docs/api.md
swagger.yaml

recommendation now has count
recommendation by userPreference has count, optional history
also updated the enums of update-pending, inbox and friends.

Swagger api update - 

---

public/myBooks/index.ejs
public/theirBooks/index.ejs

Added HTML elements for inbox to myBooks and theirBooks pages (which I should have done when adding the inbox.js scripts to these files...😅)

OK, FINAL UI edits
